apiVersion: v1
kind: Service
metadata:
  name: monioring-service
spec:
  selector:
    app: monitoring
  type: LoadBalancer
  externalIPs:
  - 3.112.237.147
  ports:
  - protocol: TCP
    name: wordpress
    port: 8080
    targetPort: 80
  - protocol: TCP
    name: prometheus
    port: 9090
    targetPort: 9090
  - protocol: TCP
    name: grafana
    port: 3000
    targetPort: 3000
  - protocol: TCP
    name: wordpress-merics
    port: 9100
    targetPort: 9100
  - protocol: TCP
    name: cadvisor
    port: 18080
    targetPort: 8080