global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'monioring-service:9100'
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['monioring-service:18080']
